apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vault
  namespace: vault
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`k8s-default-traefik-9f05a1451e-075f55d8df8dec9d.elb.ap-southeast-1.amazonaws.com`) && PathPrefix(`/vault`)
    kind: Rule
    services:
    - name: vault-ui
      port: 8200