apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vault
  namespace: vault
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`chat.surawattest.online`) && PathPrefix(`/vault`)
    kind: Rule
    services:
    - name: vault-ui
      port: 8200