apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vault
  namespace: vault
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`api-aichat-k8s-surawattes-71qf3c-845b489f340fca43.elb.ap-southeast-1.amazonaws.com`) && PathPrefix(`/vault`)
    kind: Rule
    services:
    - name: vault-ui
      port: 8200