defaultVaultConnection:
  enabled: true
  address: "http://vault.vault.svc.cluster.local:8200"
  skipTLSVerify: false
controller:
  manager:
    clientCache:
      persistenceModel: direct-encrypted
      storageEncryption:
        enabled: true
        mount: vso-auth
        keyName: vso-client-cache
        transitMount: vso-tansit
        kubernetes:
          role: vso-non-prod
          serviceAccount: vault-secrets-operator
          tokenAudiences: ["vault"]