defaultVaultConnection:
  enabled: true
  address: "http://vault.vault.svc.cluster.local:8200"
  skipTLSVerify: true
controller:
  replicas: 1
  nodeSelector: {}
  tolerations: []
  affinity: {}
defaultAuthMethod:
  enabled: true
  kubernetes:
    servuiceAccount: vault-secrets-operator