apiVersion: v1
kind: Secret
metadata:
    name: vault-aws-kms-user
    namespace: vault
stringData:
    AWS_ACCESS_KEY_ID: 
    AWS_SECRET_ACCESS_KEY: 
    AWS_KEY_ID: 
    AWS_REGION: 
    ENDPOIMT: 