apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: ops
  source:
    path: ops-deployment/overlay/traefik
    repoURL: https://github.com/surawat-prem/ai-chat
    targetRevision: non-prod