apiVersion: v1
kind: PersistentVolume
metadata:
  name: cnpg-pv
  labels:
    purpose: cnpg-jbod
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 30Gi
  hostPath:
    path: /data/cnpg-pv
  storageClassName: standard
