resources: []

helmGlobals:
  chartHome: ../../base/cnpg/charts

helmCharts:
  - releaseName: cnpg-operator
    namespace: database
    name: cnpg-operator
    includeCRDs: true
    valuesFile: ./cnpg-operator-values.yaml
    repo: ""

  - releaseName: cnpg-cluster
    namespace: database
    name: cnpg-cluster
    includeCRDs: true
    valuesFile: ./cnpg-cluster-values.yaml
    repo: ""