apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  labels:
    addon.kops.k8s.io/name: aws-load-balancer-controller.addons.k8s.io
    app: aws-load-balancer-controller
    app.kubernetes.io/managed-by: kops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-load-balancer-controller
  template:
    metadata:
      labels:
        app: aws-load-balancer-controller
    spec:
      serviceAccountName: aws-load-balancer-controller  # Ensure this service account exists
      containers:
      - name: aws-load-balancer-controller
        image: public.ecr.aws/eks/aws-load-balancer-controller:v2.9.1  # Check for the latest version
        args:
          - --cluster-name=aichat-k8s.surawattest.online  # Replace with your cluster name
          - --ingress-class=alb
          - --v=2
        ports:
          - containerPort: 9443
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 1000m
            memory: 256Mi