apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app
resources:
  - ./deployment.yaml
  - ./service.yaml
  # - ./service-account.yaml
configMapGenerator:
  - name: chat-fe
    envs:
      - .env
images:
  - newTag: v1