apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd-config/cluster-app/kustomization.yaml
    repoURL: https://github.com/surawat-prem/ai-chat
    targetRevision: non-prod