---
- name: Create cluster config with kops
  ansible.builtin.shell: |
    export KOPS_STATE_STORE=s3://{{ S3_NAME }}
    export AWS_ACCESS_KEY_ID={{ AWS_ACCESS_KEY_ID }}
    export AWS_SECRET_ACCESS_KEY={{ AWS_SECRET_ACCESS_KEY }}
    kops create cluster {{ NAME }} \
      --dns {{ DNS_TYPE }} \
      --dns-zone {{ PRIVATE_DNS_NAME }} \
      --network-id {{ VPC_ID }} \
      --topology {{ TOPOLOGY }} \
      --control-plane-count {{ CONTROL_PLANE_NODE_COUNT }} \
      --control-plane-size {{ CONTROL_PLANE_SIZE }} \
      --control-plane-zones {{ CONTROL_PLANE_ZONE }} \
      --node-count {{ NODE_COUNT }} \
      --node-size {{ NODE_SIZE }} \
      --zones {{ ZONES }} \
      --yes

- name: Export kubeconfig
  ansible.builtin.shell: |
    export KOPS_STATE_STORE=s3://{{ S3_NAME }}
    export AWS_ACCESS_KEY_ID={{ AWS_ACCESS_KEY_ID }}
    export AWS_SECRET_ACCESS_KEY={{ AWS_SECRET_ACCESS_KEY }}
    kops export kubeconfig --name {{ NAME }} --admin

- name: Verify cluster creation
  ansible.builtin.shell: |
    export KOPS_STATE_STORE=s3://{{ S3_NAME }}
    export AWS_ACCESS_KEY_ID={{ AWS_ACCESS_KEY_ID }}
    export AWS_SECRET_ACCESS_KEY={{ AWS_SECRET_ACCESS_KEY }}
    kops validate cluster --name {{ NAME }} --wait 10m
  changed_when: false
  register: cluster_validation

- name: Output cluster validation result
  ansible.builtin.debug:
    var: cluster_validation.stdout
