---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack: argocd-aichat-slack-bot
spec:
  description: Argocd Project for deploying argocd crds
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - https://github.com/surawat-prem/ai-chat
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: app
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ops
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack: argocd-aichat-slack-bot
spec:
  description: Argocd Project for deploying argocd crds
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - https://github.com/surawat-prem/ai-chat
  # Only permit applications to deploy to the guestbook namespace in the same cluster
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
  - namespace: kafka
    server: https://kubernetes.default.svc
  - namespace: vault
    server: https://kubernetes.default.svc
  - namespace: database
    server: https://kubernetes.default.svc
  - namespace: app
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'