apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: app
resources:
  - ./deployment.yaml
  - ./service.yaml
configMapGenerator:
  - name: chat-backend
    envs:
      - .env
images:
  - newTag: 20240925-192