apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv
  labels:
    purpose: kafka-jbod
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 30Gi
  hostPath:
    path: /data/kafka-pv
  storageClassName: gp2
