apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jbod-0-pvc
  namespace: kafka
  labels:
    purpose: jbod-0
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi