apiVersion: v1
kind: PersistentVolume
metadata:
  name: jbod0-pv
  namespace: kafka
  labels:
    type: jbod-0
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: default
  persistentVolumeReclaimPolicy: Retain