apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv
  annotations:
    purpose: kafka-jbod
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 30Gi
  hostPath:
    path: /data/kafka-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-jbod-0
  namespace: kafka
  annotations:
    pupose: kafka-jbod-0
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      purpose: kafka