replicaCount: 1

image:
  repository: emberstack/kubernetes-reflector
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

configuration:
  logging:
    minimumLevel: Information
  watcher:
    timeout: ""
  kubernetes:
    skipTlsVerify: false

rbac:
  enabled: true

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
extraEnv: []

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

healthcheck:
  httpGet:
    path: /healthz
    port: http

livenessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10
readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10
startupProbe:
  # The application will have a maximum of 50s (10 * 5 = 50s) to finish its startup.
  failureThreshold: 10
  periodSeconds: 5

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

priorityClassName: ""
