apiVersion: v2
appVersion: 7.1.288
description: A Helm chart to deploy Reflector
home: https://github.com/emberstack/kubernetes-reflector
icon: https://raw.githubusercontent.com/emberstack/CDN/main/projects/helm-charts/generic/emberstack_icon.png
keywords:
- reflector
- controller
- copy
- secrets
- configmaps
- cert-manager
- certificates
maintainers:
- email: helm-charts@emberstack.com
  name: winromulus
name: reflector
sources:
- https://github.com/emberstack/kubernetes-reflector
type: application
version: 7.1.288
