resources:
  - ../../../base/chat-server

configMapGenerator:
  - name: chat-server
    envs:
      - .env

images:
  - name: surawatprem/chat-server
    newTag: 20241014-570

patches:
  - target:
      kind: VaultSecret
      name: chat-server
    patch: |-
      - op: replace
        path: /spec/path
        value: kv/non-prod/chat-server
  - target:
      kind: KafkaUser
      name: chat-server-kafka-user
    patch: |-
      - op: replace
        path: /metadata/name
        value: non-prod-chat-server-kafka-user
  - target:
      kind: KafkaUser
      name: chat-server-kafka-user
    patch: |-
      - op: replace
        path: /spec/authorization/acls/0/resource/name
        value: non-prod-
  - target:
      kind: KafkaUser
      name: chat-server-kafka-user
    patch: |-
      - op: replace
        path: /spec/template/secret/metadata/annotations/reflector.v1.k8s.emberstack.com~1reflection-allowed-namespaces
        value: non-prod
  - target:
      kind: Secret
      name: chat-server-kafka-user
    patch: |-
      - op: replace
        path: /metadata/annotations/reflector.v1.k8s.emberstack.com~1reflects
        value: kafka/non-prod-chat-server-kafka-user