CREATE USER user1 WITH PASSWORD 'password1';
CREATE USER user2 WITH PASSWORD 'password2';

GRANT SELECT, INSERT, UPDATE, DELETE ON messages TO user1;
GRANT SELECT, INSERT, UPDATE, DELETE ON messages TO user2;

GRANT USAGE ON SCHEMA public TO user1;
GRANT USAGE ON SCHEMA public TO user2;
