resources:
  - ../../../base/chat-backend

namespace: non-prod

# configMapGenerator:
#   - name: chat-backend
#     envs:
#       - .env

# images:
#   - newTag: 20240925-192

patches:
  # - target:
  #     kind: VaultSecret
  #     name: chat-backend
  #   patch: |-
  #     - op: replace
  #       path: /spec/path
  #       value: kv/non-prod/chat-backend
  - target:
      kind: KafkaUser
      name: chat-backend-kafka-user
    patch: |-
      - op: replace
        path: /metadata/name
        value: non-prod-chat-backend-kafka-user
  - target:
      kind: KafkaUser
      name: chat-backend-kafka-user
    patch: |-
      - op: replace
        path: /spec/template/secret/metadata/annotations/reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces
        value: non-prod
  # - target:
  #     kind: Secret
  #     name: chat-backend-kafka-user
  #   patch: |-
  #     - op: replace
  #       path: /metadata/annotations/reflector.v1.k8s.emberstack.com/reflects
  #       value: kafka/non-prod-chat-backend-kafka-user