name: Build and Deploy Microservices

on:
  workflow_dispatch:
    inputs:
      services:
        description: 'List of changed services'
        required: true
        default: ''

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up date and random number tag
        id: tag
        run: |
          DATE=$(date +'%Y%m%d')
          RANDOM_NUMBER=$(( RANDOM % 1000 ))
          TAG="${DATE}-${RANDOM_NUMBER}"
          echo "TAG=${TAG}" >> $GITHUB_ENV

      - name: Build Docker images
        run: |
          IFS=',' read -r -a services <<< "${{ github.event.inputs.services }}"
          for service in "${services[@]}"; do
            docker build --platform=linux/amd64 -t surawatprem/${service}:${{ env.TAG }} ./microservices/${service}/
            docker push surawatprem/${service}:${{ env.TAG }}
            sed -i "s|newTag: .*|newTag: ${{ env.TAG }}|" ./app-deployment/${service}/kustomization.yaml
          done
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add app-deployment/*/kustomization.yaml
          git commit -m "Update kustomization.yaml for changed services"
          git push
