name: Check for Microservice Changes

on:
  push:
    branches:
      - non-prod
    paths:
      - 'microservices/**'
  # pull_request:
  #   branches:
  #     - non-prod

jobs:
  check_changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get changed microservices
        id: changes
        run: |
          # Get the list of changed microservices
          CHANGED_SERVICES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- microservice/** | cut -d '/' -f 1 | uniq)
          echo "::set-output name=services::$CHANGED_SERVICES"
          echo "$CHANGED_SERVICES"

      - name: Dispatch workflows for changed microservices
        if: steps.changes.outputs.services != ''
        run: |
          for service in ${{ steps.changes.outputs.services }}; do
            echo "Dispatching workflow for $service"
            gh workflow run '.github/build-and-deploy.yml' --ref ${{ github.ref }} -f service=$service
          done
