name: Build and Push Docker Images

on:
  workflow_dispatch:
    inputs:
      changed_apps:
        description: 'Comma-separated list of changed apps'
        required: true
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up date and random number tag
        id: tag
        run: |
          DATE=$(date +'%Y%m%d')
          RANDOM_NUMBER=$(( RANDOM % 1000 ))
          TAG="${DATE}-${RANDOM_NUMBER}"
          echo "TAG=${TAG}" >> $GITHUB_ENV

      - name: Build and Push Docker Images
        run: |
          IFS=',' read -ra APPS <<< "${{ github.event.inputs.changed_apps }}"
          for app in "${APPS[@]}"; do
            docker build -t surawatprem/${app}:${{ env.TAG }} ./microservices/${app}
            docker push surawatprem/${app}:${{ env.TAG }}
            sed -i "s|newTag: .*|newTag: ${TAG}|" ./app-deployment/${app}/kustomization.yaml
            git config --global user.name 'github-actions'
            git config --global user.email 'actions@github.com'
            git add ./app-deployment/${app}/kustomization.yaml
            git commit -m "Update kustomization.yaml for ${app} to new tag ${TAG}"
            git push
          done
