{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "vault-secrets-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "vault-secrets-operator.labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
{{ include "vault-secrets-operator.matchLabels" . | indent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- if .Values.serviceMonitor.enabled }}
    # Allow prometheus scrapes
    - ports:
        - port: 8080
    {{- end }}
  egress:
    # Allow DNS resolution
    - ports:
        - port: 53
          protocol: TCP
        - port: 53
          protocol: UDP
    {{- if .Values.networkPolicy.egress }}
    {{ toYaml .Values.networkPolicy.egress | nindent 4 }}
    {{- end }}
{{- end }}
