{{- if .Values.serviceAccount.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "vault-secrets-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "vault-secrets-operator.labels" . | indent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ template "vault-secrets-operator.serviceAccountName" . }}
type: kubernetes.io/service-account-token
{{- end }}
