{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "vault-secrets-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "vault-secrets-operator.labels" . | indent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{ end }}
