apiVersion: v1
kind: Service
metadata:
  name: {{ include "vault-secrets-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "vault-secrets-operator.labels" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
    - port: 8081
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "vault-secrets-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
